apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expense-tracker-staging
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/alonshak/expense-tracker-gitops.git
    targetRevision: main
    path: apps/expense-tracker/staging
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
